import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Paper Invitations (10 products)
        {
            name: 'Elegant Floral Border Invitation',
            description: 'Classic wedding invitation featuring delicate floral borders in rose gold foil. Printed on premium 300gsm cardstock with matching envelope. Customizable with your wedding details, names, and venue information. Available in ivory, blush pink, and soft cream. Size: 5x7 inches. Perfect for traditional and garden weddings.',
            price: 4.50,
            category: 'Paper Invitations',
            image: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800',
            createdAt: new Date('2024-11-15').toISOString(),
            updatedAt: new Date('2024-11-15').toISOString(),
        },
        {
            name: 'Modern Minimalist Card',
            description: 'Contemporary design with clean lines and elegant typography. Features gold foil accents on smooth white cardstock. Includes RSVP card and details insert. Fully customizable text and color options available. Size: 5x7 inches. Ideal for modern, sophisticated weddings.',
            price: 3.75,
            category: 'Paper Invitations',
            image: 'https://images.unsplash.com/photo-1545776433-5a8a88dc6db6?w=800',
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },
        {
            name: 'Vintage Lace Pattern Invitation',
            description: 'Romantic vintage-inspired design with intricate lace pattern overlay. Printed on textured linen cardstock with kraft envelope. Features pearl embellishment and satin ribbon tie. Customizable with wedding information. Available in champagne, ivory, and dusty rose. Size: 5x7 inches.',
            price: 5.25,
            category: 'Paper Invitations',
            image: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800',
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            name: 'Botanical Greenery Suite',
            description: 'Fresh and organic design featuring watercolor eucalyptus and greenery. Includes main invitation, RSVP card, and details card. Printed on eco-friendly recycled cardstock. Fully customizable with your wedding details. Size: 5x7 inches. Perfect for outdoor and rustic weddings.',
            price: 4.00,
            category: 'Paper Invitations',
            image: 'https://images.unsplash.com/photo-1587271339545-f9e6e8e5b2f7?w=800',
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            name: 'Royal Blue and Gold Invitation',
            description: 'Luxurious design with deep royal blue background and gold foil detailing. Features ornate border design and elegant script font. Printed on premium shimmer cardstock. Includes matching envelope with gold liner. Size: 5x7 inches. Suitable for formal and traditional weddings.',
            price: 6.50,
            category: 'Paper Invitations',
            image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800',
            createdAt: new Date('2024-12-08').toISOString(),
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        {
            name: 'Rustic Kraft Paper Card',
            description: 'Charming rustic design on natural kraft cardstock with twine tie. Features hand-drawn floral illustrations and casual typography. Includes RSVP postcard. Customizable with wedding information. Size: 5x7 inches. Perfect for barn weddings and casual celebrations.',
            price: 2.50,
            category: 'Paper Invitations',
            image: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800',
            createdAt: new Date('2024-12-10').toISOString(),
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            name: 'Blush Pink Watercolor Suite',
            description: 'Romantic watercolor design in soft blush pink and peach tones. Full wedding suite includes invitation, RSVP, details card, and thank you card. Printed on smooth premium cardstock. Customizable text and color variations available. Size: 5x7 inches.',
            price: 5.75,
            category: 'Paper Invitations',
            image: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800',
            createdAt: new Date('2024-12-12').toISOString(),
            updatedAt: new Date('2024-12-12').toISOString(),
        },
        {
            name: 'Monogram Elegance Card',
            description: 'Sophisticated design featuring custom monogram in gold foil. Classic typography on white premium cardstock. Includes matching envelope with wax seal. Fully customizable with names and wedding details. Size: 5x7 inches. Ideal for traditional and formal weddings.',
            price: 7.00,
            category: 'Paper Invitations',
            image: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=800',
            createdAt: new Date('2024-12-15').toISOString(),
            updatedAt: new Date('2024-12-15').toISOString(),
        },
        {
            name: 'Geometric Modern Suite',
            description: 'Contemporary geometric pattern design in navy and copper. Features clean lines and modern typography. Includes invitation, RSVP, and details insert. Printed on premium matte cardstock. Customizable colors and text. Size: 5x7 inches. Perfect for modern urban weddings.',
            price: 4.25,
            category: 'Paper Invitations',
            image: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800',
            createdAt: new Date('2024-12-18').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },
        {
            name: 'Timeless Classic White Card',
            description: 'Elegant and timeless design in pure white with black letterpress printing. Features traditional typography and simple border detail. Includes premium cotton envelope. Fully customizable wedding information. Size: 5x7 inches. Suitable for any wedding style.',
            price: 8.00,
            category: 'Paper Invitations',
            image: 'https://images.unsplash.com/photo-1511795267324-e5dc1d6b7b3f?w=800',
            createdAt: new Date('2024-12-20').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        
        // Acrylic Invitations (8 products)
        {
            name: 'Rose Gold Acrylic Card',
            description: 'Stunning transparent acrylic invitation with rose gold printing. UV printed for vibrant, long-lasting color. Includes matching acrylic envelope box. Customizable with wedding details and design. Size: 5x7 inches, 3mm thick. Perfect for modern luxury weddings.',
            price: 12.50,
            category: 'Acrylic Invitations',
            image: 'https://images.unsplash.com/photo-1516914943479-89db7d9ae7f2?w=800',
            createdAt: new Date('2024-11-18').toISOString(),
            updatedAt: new Date('2024-11-18').toISOString(),
        },
        {
            name: 'Clear Acrylic with Gold Foil',
            description: 'Modern transparent acrylic card featuring elegant gold foil text and design elements. High-quality UV printing on premium acrylic. Comes with protective sleeve. Fully customizable layout and information. Size: 5x7 inches, 3mm thick. Ideal for contemporary weddings.',
            price: 13.00,
            category: 'Acrylic Invitations',
            image: 'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?w=800',
            createdAt: new Date('2024-11-22').toISOString(),
            updatedAt: new Date('2024-11-22').toISOString(),
        },
        {
            name: 'Frosted Acrylic Suite',
            description: 'Elegant frosted acrylic invitation with white printing. Soft-touch finish creates a sophisticated look. Includes RSVP card and details insert in matching frosted acrylic. Customizable design and text. Size: 5x7 inches, 3mm thick. Perfect for winter or glamorous weddings.',
            price: 15.00,
            category: 'Acrylic Invitations',
            image: 'https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=800',
            createdAt: new Date('2024-11-25').toISOString(),
            updatedAt: new Date('2024-11-25').toISOString(),
        },
        {
            name: 'Minimalist Clear Acrylic',
            description: 'Ultra-modern minimalist design on crystal-clear acrylic. Features clean typography and simple geometric elements. UV printed for durability and clarity. Includes premium acrylic holder. Customizable with wedding information. Size: 5x7 inches, 3mm thick.',
            price: 11.00,
            category: 'Acrylic Invitations',
            image: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800',
            createdAt: new Date('2024-11-28').toISOString(),
            updatedAt: new Date('2024-11-28').toISOString(),
        },
        {
            name: 'Floral Acrylic Design',
            description: 'Beautiful transparent acrylic with vibrant floral illustration. Full-color UV printing showcases intricate details. Includes protective sleeve and gift box option. Customizable text and color scheme. Size: 5x7 inches, 3mm thick. Suitable for garden and romantic weddings.',
            price: 10.50,
            category: 'Acrylic Invitations',
            image: 'https://images.unsplash.com/photo-1504890001746-a9a68eda46e2?w=800',
            createdAt: new Date('2024-12-02').toISOString(),
            updatedAt: new Date('2024-12-02').toISOString(),
        },
        {
            name: 'Marble Effect Acrylic',
            description: 'Luxurious white marble effect printed on clear acrylic. Gold foil accents add elegance. UV printed for high-quality finish. Comes with matching acrylic stand. Fully customizable design. Size: 5x7 inches, 3mm thick. Perfect for upscale modern weddings.',
            price: 14.00,
            category: 'Acrylic Invitations',
            image: 'https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?w=800',
            createdAt: new Date('2024-12-06').toISOString(),
            updatedAt: new Date('2024-12-06').toISOString(),
        },
        {
            name: 'Black and White Acrylic',
            description: 'Bold contemporary design with black printing on clear acrylic. Features modern typography and geometric patterns. UV printed for sharp contrast. Includes protective packaging. Customizable layout and information. Size: 5x7 inches, 3mm thick.',
            price: 9.50,
            category: 'Acrylic Invitations',
            image: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800',
            createdAt: new Date('2024-12-09').toISOString(),
            updatedAt: new Date('2024-12-09').toISOString(),
        },
        {
            name: 'Hexagon Shaped Acrylic',
            description: 'Unique hexagon-shaped transparent acrylic invitation. Custom die-cut shape with elegant printing. Full-color UV printing available. Includes special hexagon display box. Customizable design and text. Size: 6x7 inches, 3mm thick. Stand out from traditional rectangular cards.',
            price: 16.00,
            category: 'Acrylic Invitations',
            image: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800',
            createdAt: new Date('2024-12-13').toISOString(),
            updatedAt: new Date('2024-12-13').toISOString(),
        },
        
        // Semi-transparent (5 products)
        {
            name: 'Frosted Vellum Overlay',
            description: 'Delicate frosted vellum overlay with elegant printing. Layered over coordinating cardstock base. Features satin ribbon tie. Customizable text and design elements. Size: 5x7 inches. Perfect for adding sophisticated dimension to invitations. Available in white, ivory, and blush.',
            price: 5.50,
            category: 'Semi-transparent',
            image: 'https://images.unsplash.com/photo-1545776433-5a8a88dc6db6?w=800',
            createdAt: new Date('2024-11-30').toISOString(),
            updatedAt: new Date('2024-11-30').toISOString(),
        },
        {
            name: 'Translucent Pearl Vellum',
            description: 'Shimmering pearl vellum with subtle iridescent finish. Semi-transparent design creates elegant layered effect. Gold foil printing option available. Includes satin bow. Customizable with wedding details. Size: 5x7 inches. Ideal for romantic and formal weddings.',
            price: 6.50,
            category: 'Semi-transparent',
            image: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800',
            createdAt: new Date('2024-12-03').toISOString(),
            updatedAt: new Date('2024-12-03').toISOString(),
        },
        {
            name: 'Botanical Vellum Wrap',
            description: 'Semi-transparent vellum featuring botanical illustrations. Wraps around main invitation card secured with wax seal. Full-color printing showcases delicate details. Customizable design and text. Size: 5x7 inches. Perfect for garden and nature-inspired weddings.',
            price: 4.75,
            category: 'Semi-transparent',
            image: 'https://images.unsplash.com/photo-1587271339545-f9e6e8e5b2f7?w=800',
            createdAt: new Date('2024-12-07').toISOString(),
            updatedAt: new Date('2024-12-07').toISOString(),
        },
        {
            name: 'Lace Pattern Vellum',
            description: 'Romantic lace pattern printed on premium vellum overlay. Semi-transparent design adds vintage elegance. Layers over colored cardstock base. Includes pearl embellishment. Customizable colors and text. Size: 5x7 inches. Suitable for classic and romantic wedding themes.',
            price: 7.25,
            category: 'Semi-transparent',
            image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800',
            createdAt: new Date('2024-12-11').toISOString(),
            updatedAt: new Date('2024-12-11').toISOString(),
        },
        {
            name: 'Watercolor Vellum Suite',
            description: 'Artistic watercolor design on translucent vellum. Features soft color gradients and modern calligraphy. Complete suite includes invitation, RSVP, and details cards. Customizable color palette. Size: 5x7 inches. Perfect for artistic and contemporary weddings.',
            price: 8.50,
            category: 'Semi-transparent',
            image: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800',
            createdAt: new Date('2024-12-16').toISOString(),
            updatedAt: new Date('2024-12-16').toISOString(),
        },
        
        // Favor Boxes (6 products)
        {
            name: 'Pearl White Favor Box',
            description: 'Elegant pearl white favor box with magnetic closure. Premium cardstock construction with smooth finish. Includes satin ribbon for decoration. Perfect for candies, chocolates, or small gifts. Size: 3x3x3 inches. Customizable with names or initials. Sold individually or in sets of 10.',
            price: 2.25,
            category: 'Favor Boxes',
            image: 'https://images.unsplash.com/photo-1511795267324-e5dc1d6b7b3f?w=800',
            createdAt: new Date('2024-11-24').toISOString(),
            updatedAt: new Date('2024-11-24').toISOString(),
        },
        {
            name: 'Kraft Pillow Box',
            description: 'Rustic kraft paper pillow-style favor box. Eco-friendly recycled material with natural finish. Easy assembly with no glue required. Perfect for rustic and outdoor weddings. Size: 4x3x1 inches. Customizable with stamps or stickers. Available in sets of 12.',
            price: 1.50,
            category: 'Favor Boxes',
            image: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800',
            createdAt: new Date('2024-11-26').toISOString(),
            updatedAt: new Date('2024-11-26').toISOString(),
        },
        {
            name: 'Gold Foil Cube Box',
            description: 'Luxurious cube-shaped box with gold foil accents. Premium white cardstock with metallic details. Features secure magnetic closure. Ideal for jewelry, macarons, or premium favors. Size: 2.5x2.5x2.5 inches. Customizable with monogram. Minimum order: 10 boxes.',
            price: 3.50,
            category: 'Favor Boxes',
            image: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=800',
            createdAt: new Date('2024-11-29').toISOString(),
            updatedAt: new Date('2024-11-29').toISOString(),
        },
        {
            name: 'Clear Window Favor Box',
            description: 'White favor box with clear acetate window. Allows guests to see contents inside. Sturdy cardstock construction with easy assembly. Perfect for displaying colorful candies or cookies. Size: 3x3x3 inches. Customizable label options available. Sets of 12 or 24.',
            price: 2.00,
            category: 'Favor Boxes',
            image: 'https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=800',
            createdAt: new Date('2024-12-04').toISOString(),
            updatedAt: new Date('2024-12-04').toISOString(),
        },
        {
            name: 'Vintage Lace Pattern Box',
            description: 'Romantic favor box with laser-cut lace pattern. Intricate design on premium ivory cardstock. Includes ribbon tie closure. Perfect for vintage and shabby chic weddings. Size: 3x3x2.5 inches. Customizable interior lining color. Available in sets of 10.',
            price: 3.00,
            category: 'Favor Boxes',
            image: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800',
            createdAt: new Date('2024-12-14').toISOString(),
            updatedAt: new Date('2024-12-14').toISOString(),
        },
        {
            name: 'Rose Gold Drawer Box',
            description: 'Modern drawer-style box with rose gold foil finish. Elegant sliding drawer design for premium presentation. Sturdy construction holds small jewelry or keepsakes. Size: 4x3x1.5 inches. Customizable with names or wedding date. Minimum order: 15 boxes.',
            price: 4.00,
            category: 'Favor Boxes',
            image: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800',
            createdAt: new Date('2024-12-17').toISOString(),
            updatedAt: new Date('2024-12-17').toISOString(),
        },
        
        // Goody Bags (5 products)
        {
            name: 'Silk Drawstring Goody Bag',
            description: 'Luxurious silk drawstring bag in multiple color options. Soft and elegant material perfect for premium favors. Features satin ribbon drawstring closure. Size: 4x6 inches. Available in white, ivory, champagne, and blush. Customizable with embroidery or printed tag. Sets of 10 or 20.',
            price: 2.50,
            category: 'Goody Bags',
            image: 'https://images.unsplash.com/photo-1545776433-5a8a88dc6db6?w=800',
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            name: 'Organza Gift Bag',
            description: 'Sheer organza bags with satin ribbon tie. Semi-transparent design shows off colorful favors inside. Lightweight and elegant option. Size: 3x4 inches. Available in 15+ colors. Perfect for candies, soaps, or small gifts. Bulk pricing available for orders over 50.',
            price: 1.00,
            category: 'Goody Bags',
            image: 'https://images.unsplash.com/photo-1511795267324-e5dc1d6b7b3f?w=800',
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            name: 'Burlap Favor Pouch',
            description: 'Rustic natural burlap pouches with jute drawstring. Eco-friendly and perfect for country or barn weddings. Durable construction holds various favor items. Size: 4x5 inches. Customizable with lace trim or printed tag. Available in natural or white. Sets of 12.',
            price: 1.75,
            category: 'Goody Bags',
            image: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800',
            createdAt: new Date('2024-12-08').toISOString(),
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        {
            name: 'Velvet Drawstring Bag',
            description: 'Premium velvet bags with elegant drape and luxurious feel. Rich jewel tone colors available. Features matching velvet drawstring. Size: 3x5 inches. Perfect for high-end favors, jewelry, or keepsakes. Customizable with embossed logo. Colors: burgundy, navy, emerald, black.',
            price: 3.50,
            category: 'Goody Bags',
            image: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=800',
            createdAt: new Date('2024-12-12').toISOString(),
            updatedAt: new Date('2024-12-12').toISOString(),
        },
        {
            name: 'Cotton Canvas Tote Bag',
            description: 'Small cotton canvas tote bags perfect for eco-friendly favors. Reusable and practical gift option. Features sturdy handles and natural cotton material. Size: 6x8 inches. Customizable with screen printing or heat transfer. Minimum order: 20 bags. Available in natural or black.',
            price: 2.75,
            category: 'Goody Bags',
            image: 'https://images.unsplash.com/photo-1587271339545-f9e6e8e5b2f7?w=800',
            createdAt: new Date('2024-12-19').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        
        // Accessories (5 products)
        {
            name: 'Wax Seal Stickers - Gold',
            description: 'Self-adhesive wax seal stickers in metallic gold. Classic design adds elegance to envelopes and invitations. No heating required, easy application. Diameter: 1 inch. Available in various monogram letters and decorative designs. Pack of 50 stickers.',
            price: 3.50,
            category: 'Accessories',
            image: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800',
            createdAt: new Date('2024-11-27').toISOString(),
            updatedAt: new Date('2024-11-27').toISOString(),
        },
        {
            name: 'Satin Ribbon Roll',
            description: 'Premium double-faced satin ribbon for invitation assemblies. Smooth and luxurious feel. Width: 5/8 inch, Length: 25 yards per roll. Available in 30+ colors to match wedding theme. Perfect for tying belly bands, bows, or creating embellishments.',
            price: 4.50,
            category: 'Accessories',
            image: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800',
            createdAt: new Date('2024-12-02').toISOString(),
            updatedAt: new Date('2024-12-02').toISOString(),
        },
        {
            name: 'Pearl Embellishment Pack',
            description: 'Adhesive pearl embellishments for invitation decoration. Self-stick backing for easy application. Mixed sizes: 3mm, 5mm, and 8mm pearls. Pack contains 200 pieces. Available in white, ivory, and champagne. Add elegant touch to invitations, favor boxes, and cards.',
            price: 2.25,
            category: 'Accessories',
            image: 'https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=800',
            createdAt: new Date('2024-12-06').toISOString(),
            updatedAt: new Date('2024-12-06').toISOString(),
        },
        {
            name: 'Decorative Envelope Liners',
            description: 'Pre-cut envelope liners with adhesive backing. Various patterns: floral, geometric, watercolor, and solid colors. Fits standard A7 envelopes (5x7 invitations). Easy to install with peel-and-stick design. Pack of 25 liners. Add professional finishing touch to invitations.',
            price: 5.00,
            category: 'Accessories',
            image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800',
            createdAt: new Date('2024-12-10').toISOString(),
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            name: 'Belly Band Kit - Assorted',
            description: 'Pre-cut belly bands for wrapping invitation suites together. Premium cardstock in coordinating colors. Size: 2x11 inches, fits 5x7 invitations. Self-adhesive or can be secured with ribbon. Pack includes 25 bands. Available in white, kraft, gold, and silver metallic.',
            price: 3.25,
            category: 'Accessories',
            image: 'https://images.unsplash.com/photo-1516914943479-89db7d9ae7f2?w=800',
            createdAt: new Date('2024-12-15').toISOString(),
            updatedAt: new Date('2024-12-15').toISOString(),
        },
        
        // Dala (3 products)
        {
            name: 'Handcrafted Mehndi Dala',
            description: 'Traditional Pakistani mehndi dala with intricate handcrafted details. Decorated with flowers, candles, and traditional elements. Includes base tray, decorative covering, and accessories. Size: 18 inches diameter. Customizable with bride and groom names. Perfect for mehndi ceremony and gift presentation.',
            price: 28.00,
            category: 'Dala',
            image: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800',
            createdAt: new Date('2024-12-03').toISOString(),
            updatedAt: new Date('2024-12-03').toISOString(),
        },
        {
            name: 'Royal Gold Dala Set',
            description: 'Luxurious gold-themed dala with ornate decorations. Features gold foil detailing, crystal embellishments, and premium fabric covering. Includes matching smaller trays for complete set. Size: 20 inches main tray. Customizable design elements. Ideal for upscale Pakistani and Indian weddings.',
            price: 35.00,
            category: 'Dala',
            image: 'https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?w=800',
            createdAt: new Date('2024-12-09').toISOString(),
            updatedAt: new Date('2024-12-09').toISOString(),
        },
        {
            name: 'Floral Garden Dala',
            description: 'Beautiful dala decorated with fresh-looking artificial flowers and greenery. Romantic garden theme with pink and white color scheme. Includes decorated tray, candles, and gift presentation elements. Size: 16 inches diameter. Customizable flower colors and arrangement. Perfect for engagement ceremonies.',
            price: 24.00,
            category: 'Dala',
            image: 'https://images.unsplash.com/photo-1504890001746-a9a68eda46e2?w=800',
            createdAt: new Date('2024-12-13').toISOString(),
            updatedAt: new Date('2024-12-13').toISOString(),
        },
        
        // Gift Envelopes (3 products)
        {
            name: 'Embossed Gift Envelope',
            description: 'Premium embossed gift envelope for cash gifts. Elegant raised pattern design on quality cardstock. Features secure flap closure. Size: 4.5x6.5 inches. Available in white, ivory, and champagne. Customizable with names or monogram. Pack of 10 envelopes.',
            price: 3.75,
            category: 'Gift Envelopes',
            image: 'https://images.unsplash.com/photo-1511795267324-e5dc1d6b7b3f?w=800',
            createdAt: new Date('2024-12-04').toISOString(),
            updatedAt: new Date('2024-12-04').toISOString(),
        },
        {
            name: 'Gold Foil Gift Envelope',
            description: 'Elegant envelope with gold foil border and design accents. Perfect for presenting monetary gifts at weddings. Premium cardstock with smooth finish. Size: 5x7 inches. Customizable interior printing option. Available in white, cream, and blush. Minimum order: 10 envelopes.',
            price: 4.50,
            category: 'Gift Envelopes',
            image: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=800',
            createdAt: new Date('2024-12-11').toISOString(),
            updatedAt: new Date('2024-12-11').toISOString(),
        },
        {
            name: 'Lace Pattern Gift Envelope',
            description: 'Romantic gift envelope featuring laser-cut lace pattern overlay. Delicate design on premium white cardstock. Includes ribbon tie closure. Size: 4.5x6 inches. Perfect for elegant weddings. Customizable with couple names or message. Sets of 12 available.',
            price: 5.25,
            category: 'Gift Envelopes',
            image: 'https://images.unsplash.com/photo-1545776433-5a8a88dc6db6?w=800',
            createdAt: new Date('2024-12-16').toISOString(),
            updatedAt: new Date('2024-12-16').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});